package com.soonfor.warehousemanager.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.soonfor.warehousemanager.bases.NetStatusBean;
import com.soonfor.warehousemanager.module.instore.beans.BarItemBean;
import com.soonfor.warehousemanager.module.instore.beans.hebao.HeBaoBarItemBean;
import com.soonfor.warehousemanager.module.instore.beans.hebao.HeBaoGoodsItem;
import com.soonfor.warehousemanager.module.instore.beans.OrdInStatusBean;
import com.soonfor.warehousemanager.module.instore.beans.OrdQitaoBean;
import com.soonfor.warehousemanager.module.outstore.beans.OutOrdInStatusBean;
import com.soonfor.warehousemanager.module.outstore.beans.OutOrdQitaoBean;
import com.soonfor.warehousemanager.module.print.bean.PrinterBean;
import com.soonfor.warehousemanager.module.print.bean.PrinterReadyBean;

import com.soonfor.warehousemanager.dao.NetStatusBeanDao;
import com.soonfor.warehousemanager.dao.BarItemBeanDao;
import com.soonfor.warehousemanager.dao.HeBaoBarItemBeanDao;
import com.soonfor.warehousemanager.dao.HeBaoGoodsItemDao;
import com.soonfor.warehousemanager.dao.OrdInStatusBeanDao;
import com.soonfor.warehousemanager.dao.OrdQitaoBeanDao;
import com.soonfor.warehousemanager.dao.OutOrdInStatusBeanDao;
import com.soonfor.warehousemanager.dao.OutOrdQitaoBeanDao;
import com.soonfor.warehousemanager.dao.PrinterBeanDao;
import com.soonfor.warehousemanager.dao.PrinterReadyBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig netStatusBeanDaoConfig;
    private final DaoConfig barItemBeanDaoConfig;
    private final DaoConfig heBaoBarItemBeanDaoConfig;
    private final DaoConfig heBaoGoodsItemDaoConfig;
    private final DaoConfig ordInStatusBeanDaoConfig;
    private final DaoConfig ordQitaoBeanDaoConfig;
    private final DaoConfig outOrdInStatusBeanDaoConfig;
    private final DaoConfig outOrdQitaoBeanDaoConfig;
    private final DaoConfig printerBeanDaoConfig;
    private final DaoConfig printerReadyBeanDaoConfig;

    private final NetStatusBeanDao netStatusBeanDao;
    private final BarItemBeanDao barItemBeanDao;
    private final HeBaoBarItemBeanDao heBaoBarItemBeanDao;
    private final HeBaoGoodsItemDao heBaoGoodsItemDao;
    private final OrdInStatusBeanDao ordInStatusBeanDao;
    private final OrdQitaoBeanDao ordQitaoBeanDao;
    private final OutOrdInStatusBeanDao outOrdInStatusBeanDao;
    private final OutOrdQitaoBeanDao outOrdQitaoBeanDao;
    private final PrinterBeanDao printerBeanDao;
    private final PrinterReadyBeanDao printerReadyBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        netStatusBeanDaoConfig = daoConfigMap.get(NetStatusBeanDao.class).clone();
        netStatusBeanDaoConfig.initIdentityScope(type);

        barItemBeanDaoConfig = daoConfigMap.get(BarItemBeanDao.class).clone();
        barItemBeanDaoConfig.initIdentityScope(type);

        heBaoBarItemBeanDaoConfig = daoConfigMap.get(HeBaoBarItemBeanDao.class).clone();
        heBaoBarItemBeanDaoConfig.initIdentityScope(type);

        heBaoGoodsItemDaoConfig = daoConfigMap.get(HeBaoGoodsItemDao.class).clone();
        heBaoGoodsItemDaoConfig.initIdentityScope(type);

        ordInStatusBeanDaoConfig = daoConfigMap.get(OrdInStatusBeanDao.class).clone();
        ordInStatusBeanDaoConfig.initIdentityScope(type);

        ordQitaoBeanDaoConfig = daoConfigMap.get(OrdQitaoBeanDao.class).clone();
        ordQitaoBeanDaoConfig.initIdentityScope(type);

        outOrdInStatusBeanDaoConfig = daoConfigMap.get(OutOrdInStatusBeanDao.class).clone();
        outOrdInStatusBeanDaoConfig.initIdentityScope(type);

        outOrdQitaoBeanDaoConfig = daoConfigMap.get(OutOrdQitaoBeanDao.class).clone();
        outOrdQitaoBeanDaoConfig.initIdentityScope(type);

        printerBeanDaoConfig = daoConfigMap.get(PrinterBeanDao.class).clone();
        printerBeanDaoConfig.initIdentityScope(type);

        printerReadyBeanDaoConfig = daoConfigMap.get(PrinterReadyBeanDao.class).clone();
        printerReadyBeanDaoConfig.initIdentityScope(type);

        netStatusBeanDao = new NetStatusBeanDao(netStatusBeanDaoConfig, this);
        barItemBeanDao = new BarItemBeanDao(barItemBeanDaoConfig, this);
        heBaoBarItemBeanDao = new HeBaoBarItemBeanDao(heBaoBarItemBeanDaoConfig, this);
        heBaoGoodsItemDao = new HeBaoGoodsItemDao(heBaoGoodsItemDaoConfig, this);
        ordInStatusBeanDao = new OrdInStatusBeanDao(ordInStatusBeanDaoConfig, this);
        ordQitaoBeanDao = new OrdQitaoBeanDao(ordQitaoBeanDaoConfig, this);
        outOrdInStatusBeanDao = new OutOrdInStatusBeanDao(outOrdInStatusBeanDaoConfig, this);
        outOrdQitaoBeanDao = new OutOrdQitaoBeanDao(outOrdQitaoBeanDaoConfig, this);
        printerBeanDao = new PrinterBeanDao(printerBeanDaoConfig, this);
        printerReadyBeanDao = new PrinterReadyBeanDao(printerReadyBeanDaoConfig, this);

        registerDao(NetStatusBean.class, netStatusBeanDao);
        registerDao(BarItemBean.class, barItemBeanDao);
        registerDao(HeBaoBarItemBean.class, heBaoBarItemBeanDao);
        registerDao(HeBaoGoodsItem.class, heBaoGoodsItemDao);
        registerDao(OrdInStatusBean.class, ordInStatusBeanDao);
        registerDao(OrdQitaoBean.class, ordQitaoBeanDao);
        registerDao(OutOrdInStatusBean.class, outOrdInStatusBeanDao);
        registerDao(OutOrdQitaoBean.class, outOrdQitaoBeanDao);
        registerDao(PrinterBean.class, printerBeanDao);
        registerDao(PrinterReadyBean.class, printerReadyBeanDao);
    }
    
    public void clear() {
        netStatusBeanDaoConfig.clearIdentityScope();
        barItemBeanDaoConfig.clearIdentityScope();
        heBaoBarItemBeanDaoConfig.clearIdentityScope();
        heBaoGoodsItemDaoConfig.clearIdentityScope();
        ordInStatusBeanDaoConfig.clearIdentityScope();
        ordQitaoBeanDaoConfig.clearIdentityScope();
        outOrdInStatusBeanDaoConfig.clearIdentityScope();
        outOrdQitaoBeanDaoConfig.clearIdentityScope();
        printerBeanDaoConfig.clearIdentityScope();
        printerReadyBeanDaoConfig.clearIdentityScope();
    }

    public NetStatusBeanDao getNetStatusBeanDao() {
        return netStatusBeanDao;
    }

    public BarItemBeanDao getBarItemBeanDao() {
        return barItemBeanDao;
    }

    public HeBaoBarItemBeanDao getHeBaoBarItemBeanDao() {
        return heBaoBarItemBeanDao;
    }

    public HeBaoGoodsItemDao getHeBaoGoodsItemDao() {
        return heBaoGoodsItemDao;
    }

    public OrdInStatusBeanDao getOrdInStatusBeanDao() {
        return ordInStatusBeanDao;
    }

    public OrdQitaoBeanDao getOrdQitaoBeanDao() {
        return ordQitaoBeanDao;
    }

    public OutOrdInStatusBeanDao getOutOrdInStatusBeanDao() {
        return outOrdInStatusBeanDao;
    }

    public OutOrdQitaoBeanDao getOutOrdQitaoBeanDao() {
        return outOrdQitaoBeanDao;
    }

    public PrinterBeanDao getPrinterBeanDao() {
        return printerBeanDao;
    }

    public PrinterReadyBeanDao getPrinterReadyBeanDao() {
        return printerReadyBeanDao;
    }

}
